### ISSUE TITLE
Video Clarifications are not Displayed

### ISSUE THREAD

**Issue by MrMagma** [JavascriptFTW/Clarif-Viewer-for-KA#2]
I noticed this problem a few days ago and originally thought that there simply were not any clarifications on videos.

After some thought it seems more likely that requests are getting sent to the wrong URL, causing the video request to either get no data or unexpected data. If the requests are going to the wrong URL it might help explain the cause for #1 as I believe some articles have the same titles as videos.

**Comment by MrMagma** [comment]
I've reviewed the code for fetching clarifications and everything seems to be working okay. I've also fetched clarifications for every topic and no video clarifications came back.

It appears that the team at KA has simply done an exceptionally good job.

I am, however, going to leave this issue open until someone spots a video clarification "in the wild".

/cc @carolinecharrow

**Comment by carolinecharrow** [comment]
We had several thousand video clarifications as of last week, and I know we haven't spent the time it would take to clear them all out, so I don't think it's that we don't have any pending.... I think the issue may be that the new version of the website (bibliotron) doesn't currently display clarifications. The eng team is slated to fix that in about two weeks - maybe when they do that we can circle back and see about making video clarifications pull through again?

**Comment by MrMagma** [comment]
Fixed by be62e4d4a00c2993d7f9bee3780b55e7fae4b69e
