### ISSUE TITLE
Possible to add AP CSP to topics list?

### ISSUE THREAD

**Issue by pamelafox** [JavascriptFTW/Clarif-Viewer-for-KA#4]
Hey there! I just released AP CSP and see it's not showing up on the list. I haven't been able to figure out where the topics data is coming from. Is it possible to get AP CSP to show up?

**Comment by MrMagma** [comment]
AP CSP should be showing up on the client now. Apologies for the delay. Let me know if there are any issues.

**Comment by pamelafox** [comment]
Thank you!
